import { Priority, Status, IssueType, User, Task, Sprint } from './types';

export const USERS: User[] = [
  {
    id: 'u1',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    role: 'Product Owner',
    avatar: 'https://i.pravatar.cc/150?u=jane',
  },
  {
    id: 'u2',
    name: 'Mike Chen',
    email: 'mike.chen@example.com',
    role: 'Frontend Dev',
    avatar: 'https://i.pravatar.cc/150?u=mike',
  },
  {
    id: 'u3',
    name: 'Sarah Smith',
    email: 'sarah.smith@example.com',
    role: 'Backend Dev',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
  },
  {
    id: 'u4',
    name: 'Alex Morgan',
    email: 'alex.m@example.com',
    role: 'Designer',
    avatar: 'https://i.pravatar.cc/150?u=alex',
  },
];

export const SPRINTS: Sprint[] = [
  {
    id: 's1',
    name: 'Sprint 24',
    startDate: 'Oct 15, 2023',
    endDate: 'Oct 29, 2023',
    goal: 'Complete authentication overhaul and initial payment integration.',
    status: 'active',
  },
  {
    id: 's2',
    name: 'Sprint 25',
    startDate: 'Oct 30, 2023',
    endDate: 'Nov 12, 2023',
    goal: 'User profile dashboard and analytics setup.',
    status: 'future',
  }
];

export const TASKS: Task[] = [
  {
    id: 't1',
    key: 'PROJ-101',
    title: 'Design Login Page authentication flow',
    description: 'We need to redesign the login flow to support MFA and Social Login (Google, GitHub).',
    status: Status.TODO,
    priority: Priority.HIGH,
    type: IssueType.TASK,
    assigneeId: 'u4',
    reporterId: 'u1',
    sprintId: 's1',
    dueDate: 'Oct 24, 2023',
    createdAt: 'Oct 10, 2023',
    updatedAt: 'Oct 12, 2023',
    labels: ['UX', 'Auth'],
    comments: [],
  },
  {
    id: 't2',
    key: 'PROJ-104',
    title: 'Set up database schema for user profiles',
    description: 'Create the initial migration files for the user table, including fields for OAuth tokens.',
    status: Status.TODO,
    priority: Priority.MEDIUM,
    type: IssueType.TASK,
    assigneeId: 'u3',
    reporterId: 'u2',
    sprintId: 's1',
    dueDate: 'Oct 25, 2023',
    createdAt: 'Oct 11, 2023',
    updatedAt: 'Oct 11, 2023',
    labels: ['Backend', 'Database'],
  },
  {
    id: 't3',
    key: 'PROJ-105',
    title: 'Integrate Stripe API for payments',
    description: 'Implement the payment intent creation flow on the backend.',
    status: Status.IN_PROGRESS,
    priority: Priority.CRITICAL,
    type: IssueType.TASK,
    assigneeId: 'u3',
    reporterId: 'u1',
    sprintId: 's1',
    dueDate: 'Oct 28, 2023',
    createdAt: 'Oct 12, 2023',
    updatedAt: 'Oct 15, 2023',
    labels: ['Backend', 'Payments'],
    subtasks: [
      { id: 'st1', title: 'Setup Stripe Account', completed: true },
      { id: 'st2', title: 'Create webhook endpoints', completed: false },
    ]
  },
  {
    id: 't4',
    key: 'PROJ-112',
    title: 'Research competitor analytics features',
    description: 'Look into Mixpanel and Amplitude to see what features we should prioritize.',
    status: Status.IN_PROGRESS,
    priority: Priority.LOW,
    type: IssueType.TASK,
    assigneeId: 'u1',
    reporterId: 'u1',
    sprintId: 's1',
    dueDate: 'Nov 01, 2023',
    createdAt: 'Oct 14, 2023',
    updatedAt: 'Oct 16, 2023',
    labels: ['Product'],
  },
  {
    id: 't5',
    key: 'PROJ-098',
    title: 'Update Readme.md with setup instructions',
    description: 'The current readme is outdated. Please update environment variable requirements.',
    status: Status.DONE,
    priority: Priority.LOW,
    type: IssueType.TASK,
    assigneeId: 'u2',
    reporterId: 'u3',
    sprintId: 's1',
    createdAt: 'Sep 30, 2023',
    updatedAt: 'Oct 05, 2023',
    labels: ['Docs'],
  },
  {
    id: 't6',
    key: 'PROJ-092',
    title: 'Fix navigation bar responsiveness on mobile',
    description: 'The hamburger menu does not open on iOS Safari.',
    status: Status.DONE,
    priority: Priority.HIGH,
    type: IssueType.BUG,
    assigneeId: 'u2',
    reporterId: 'u4',
    sprintId: 's1',
    createdAt: 'Sep 28, 2023',
    updatedAt: 'Oct 02, 2023',
    labels: ['Frontend', 'Bug'],
  },
  {
    id: 't7',
    key: 'PROJ-120',
    title: 'Implement Dark Mode Toggle',
    description: 'Allow users to switch between light and dark themes.',
    status: Status.REVIEW,
    priority: Priority.MEDIUM,
    type: IssueType.TASK,
    assigneeId: 'u2',
    reporterId: 'u1',
    sprintId: 's1',
    createdAt: 'Oct 18, 2023',
    updatedAt: 'Oct 20, 2023',
    labels: ['Frontend', 'UX'],
  },
  {
    id: 't8',
    key: 'PROJ-122',
    title: 'Create User Dashboard Wireframes',
    description: 'Initial low-fi wireframes for the user settings area.',
    status: Status.TODO,
    priority: Priority.MEDIUM,
    type: IssueType.TASK,
    assigneeId: 'u4',
    reporterId: 'u1',
    sprintId: 's2',
    dueDate: 'Nov 05, 2023',
    createdAt: 'Oct 20, 2023',
    updatedAt: 'Oct 20, 2023',
    labels: ['UX', 'Design'],
  }
];

export const REPORT_DATA = [
  { name: 'Day 1', ideal: 100, actual: 100 },
  { name: 'Day 3', ideal: 85, actual: 92 },
  { name: 'Day 5', ideal: 70, actual: 85 },
  { name: 'Day 7', ideal: 55, actual: 65 },
  { name: 'Day 10', ideal: 40, actual: 45 },
  { name: 'Day 12', ideal: 25, actual: 30 },
  { name: 'Day 14', ideal: 10, actual: 15 },
];

export const TICKET_DISTRIBUTION = [
  { name: 'Features', value: 64, color: '#3b82f6' },
  { name: 'Bugs', value: 36, color: '#ef4444' },
  { name: 'Tasks', value: 43, color: '#f59e0b' },
];
